### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by schmidh** [xapi-project/xen-api-client#33]
Could we make the latest release (v0.9.9) available for opam? Version 0.9.8 does not install - at least not with ocaml 4.02.3.

Thanks!

**Comment by schmidh** [comment]
Sorry, nothing to do with the two latest versions as the relevant files are the same. Here is the error log:

#=== ERROR while installing xen-api-client.0.9.8 ==============================#
# opam-version 1.2.2
# os           linux
# command      make
# compiler     4.02.3
....
# File "async/xen_api_async_unix.ml", line 109, characters 3-17:
# Error: This function has type
#          'a ->
#          [> `Probably_should_not_use_blocking_Core_Printf_functions_with_Async ]
#        It is applied to too many arguments; maybe you forgot a `;'.
# Command exited with code 2.

Doesn't make a lot of sense to me. But you know the code better than me. ;-) 
(I have updated opam to latest versions.)

**Comment by djs55** [comment]
Ah yeah I know the problem-- I've been caught cheating, mixing blocking
calls with async calls. I'll take a look later...
