### ISSUE TITLE
References are just strings

### ISSUE THREAD

**Issue by gaborigloi** [xapi-project/xen-api-client#52]
Why does `VBD.create` from `xen-api-client` return a `string` instead of a VBD ref? :thinking_face: Noticed that this is true for all functions in `Xen_api_lwt_unix` - references are just strings.

**Comment by gaborigloi** [comment]
Plan: for now, just regenerate it. But next time we should make this depend on `xapi-client` to ensure we automatically use up-to-date bindings. This depends on the `opam` files of xapi getting updated.

**Comment by gaborigloi** [comment]
The reason for this is that `aPI.ml` has its own `Ref` module, and its `'a t` type is transparent, so users know that it's represented as a string:

https://github.com/xapi-project/xen-api-client/blob/dd78a8bdfaff17f6346ed6b5a3dab6e0f969dac1/lib/aPI.ml#L24-L30

I think making this type opaque by adding a signature to the `Ref` module should fix the problem.

**Comment by gaborigloi** [comment]
This change might break some code though, that used the existing `string` type for references. (It will definitely break my code in xapi-nbd 🤣 .) But it will provide extra safety, we should definitely do it ASAP if it's not too risky.

**Comment by gaborigloi** [comment]
This problem is not related to the autogeneration, I had to manually change this module in c04adbeafcf5ada905fd0a4f95c00745e6157e33 to fix compilation, when moving this lib to PPX.

**Comment by mseri** [comment]
Not currently. Now that `xapi` has been ported to `jbuilder` and `xapi-client` is its own library, we should instead make this bindings depend on it but it's going to take a while before everithing is in place for this
